---
- name: restart strongswan
  systemd:
    name: strongswan
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart networking
  systemd:
    name: networking
    state: restarted